development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mba_development
  pool: 5
  username: root
  password: "Mys3267!"
  host: 172.17.0.2
  # host: mba-legacy-mysql

production:
  adapter: mysql
  host: mba-legacy-mysql
  port: 10000
  database: mba_development
  username: mysql
  password: MySecretPassword22!
  encoding: utf8
  timeout: 5000
#   estraier:
#     host: 10.176.67.72
#     user: globalauth
#     password: SoniC$NeW33Nates
#     port: 1978
#     node: globalauth

# legacy:
#   production:
#     adapter: mysql
#     host: 10.176.160.74
#     port: 3306
#     database: GA_dbo
#     username: globalauth
#     password: mas75VaSes#
#     encoding: utf8
#     timeout: 5000