databases:
  - name: MBA-Legacy-MySQL
    databaseName: mba_development
    user: mba

services:
  - type: web
    name: mysite
    env: docker
    dockerCommand: "/bin/bash"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false